[tool.poetry]
name = "music-python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "2024.7.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
