[tool.poetry]
name = "music-python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "2025.6.30"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
